function SetImage(arr) {
    arr[0].picture = "<img src = \"image/blue%20cat%20empty.png\">";
    arr[1].picture = "<img src = \"image/blue%20cat%20empty.png\"><img src = \"image/blue%20cat%20empty.png\">";
    arr[2].picture = "<img src = \"image/blue%20cat%20empty.png\"><img src = \"image/blue%20cat%20empty.png\"><img src = \"image/blue%20cat%20empty.png\">";
    arr[3].picture = "<img src = \"image/blue%20cat%20stripe.png\">";
    arr[4].picture = "<img src = \"image/blue%20cat%20stripe.png\"><img src = \"image/blue%20cat%20stripe.png\">";
    arr[5].picture = "<img src = \"image/blue%20cat%20stripe.png\"><img src = \"image/blue%20cat%20stripe.png\"><img src = \"image/blue%20cat%20stripe.png\">";
    arr[6].picture = "<img src = \"image/blue%20cat%20full.png\">";
    arr[7].picture = "<img src = \"image/blue%20cat%20full.png\"><img src = \"image/blue%20cat%20full.png\">";
    arr[8].picture = "<img src = \"image/blue%20cat%20full.png\"><img src = \"image/blue%20cat%20full.png\"><img src = \"image/blue%20cat%20full.png\">";
    arr[9].picture = "<img src = \"image/blue%20paw%20empty.png\">";
    arr[10].picture = "<img src = \"image/blue%20paw%20empty.png\"><img src = \"image/blue%20paw%20empty.png\">";
    arr[11].picture = "<img src = \"image/blue%20paw%20empty.png\"><img src = \"image/blue%20paw%20empty.png\"><img src = \"image/blue%20paw%20empty.png\">";
    arr[12].picture = "<img src = \"image/blue%20paw%20stripe.png\">";
    arr[13].picture = "<img src = \"image/blue%20paw%20stripe.png\"><img src = \"image/blue%20paw%20stripe.png\">";
    arr[14].picture = "<img src = \"image/blue%20paw%20stripe.png\"><img src = \"image/blue%20paw%20stripe.png\"><img src = \"image/blue%20paw%20stripe.png\">";
    arr[15].picture = "<img src = \"image/blue%20paw%20full.png\">";
    arr[16].picture = "<img src = \"image/blue%20paw%20full.png\"><img src = \"image/blue%20paw%20full.png\">";
    arr[17].picture = "<img src = \"image/blue%20paw%20full.png\"><img src = \"image/blue%20paw%20full.png\"><img src = \"image/blue%20paw%20full.png\">";
    arr[18].picture = "<img src = \"image/blue%20fish%20empty.png\">";
    arr[19].picture = "<img src = \"image/blue%20fish%20empty.png\"><img src = \"image/blue%20fish%20empty.png\">";
    arr[20].picture = "<img src = \"image/blue%20fish%20empty.png\"><img src = \"image/blue%20fish%20empty.png\"><img src = \"image/blue%20fish%20empty.png\">";
    arr[21].picture = "<img src = \"image/blue%20fish%20stripe.png\">";
    arr[22].picture = "<img src = \"image/blue%20fish%20stripe.png\"><img src = \"image/blue%20fish%20stripe.png\">";
    arr[23].picture = "<img src = \"image/blue%20fish%20stripe.png\"><img src = \"image/blue%20fish%20stripe.png\"><img src = \"image/blue%20fish%20stripe.png\">";
    arr[24].picture = "<img src = \"image/blue%20fish%20full.png\">";
    arr[25].picture = "<img src = \"image/blue%20fish%20full.png\"><img src = \"image/blue%20fish%20full.png\">";
    arr[26].picture = "<img src = \"image/blue%20fish%20full.png\"><img src = \"image/blue%20fish%20full.png\"><img src = \"image/blue%20fish%20full.png\">";
    arr[27].picture = "<img src = \"image/red%20cat%20empty.png\">";
    arr[28].picture = "<img src = \"image/red%20cat%20empty.png\"><img src = \"image/red%20cat%20empty.png\">";
    arr[29].picture = "<img src = \"image/red%20cat%20empty.png\"><img src = \"image/red%20cat%20empty.png\"><img src = \"image/red%20cat%20empty.png\">";
    arr[30].picture = "<img src = \"image/red%20cat%20stripe.png\">";
    arr[31].picture = "<img src = \"image/red%20cat%20stripe.png\"><img src = \"image/red%20cat%20stripe.png\">";
    arr[32].picture = "<img src = \"image/red%20cat%20stripe.png\"><img src = \"image/red%20cat%20stripe.png\"><img src = \"image/red%20cat%20stripe.png\">";
    arr[33].picture = "<img src = \"image/red%20cat%20full.png\">";
    arr[34].picture = "<img src = \"image/red%20cat%20full.png\"><img src = \"image/red%20cat%20full.png\">";
    arr[35].picture = "<img src = \"image/red%20cat%20full.png\"><img src = \"image/red%20cat%20full.png\"><img src = \"image/red%20cat%20full.png\">";
    arr[36].picture = "<img src = \"image/red%20paw%20empty.png\">";
    arr[37].picture = "<img src = \"image/red%20paw%20empty.png\"><img src = \"image/red%20paw%20empty.png\">";
    arr[38].picture = "<img src = \"image/red%20paw%20empty.png\"><img src = \"image/red%20paw%20empty.png\"><img src = \"image/red%20paw%20empty.png\">";
    arr[39].picture = "<img src = \"image/red%20paw%20stripe.png\">";
    arr[40].picture = "<img src = \"image/red%20paw%20stripe.png\"><img src = \"image/red%20paw%20stripe.png\">";
    arr[41].picture = "<img src = \"image/red%20paw%20stripe.png\"><img src = \"image/red%20paw%20stripe.png\"><img src = \"image/red%20paw%20stripe.png\">";
    arr[42].picture = "<img src = \"image/red%20paw%20full.png\">";
    arr[43].picture = "<img src = \"image/red%20paw%20full.png\"><img src = \"image/red%20paw%20full.png\">";
    arr[44].picture = "<img src = \"image/red%20paw%20full.png\"><img src = \"image/red%20paw%20full.png\"><img src = \"image/red%20paw%20full.png\">";
    arr[45].picture = "<img src = \"image/red%20fish%20empty.png\">";
    arr[46].picture = "<img src = \"image/red%20fish%20empty.png\"><img src = \"image/red%20fish%20empty.png\">";
    arr[47].picture = "<img src = \"image/red%20fish%20empty.png\"><img src = \"image/red%20fish%20empty.png\"><img src = \"image/red%20fish%20empty.png\">";
    arr[48].picture = "<img src = \"image/red%20fish%20stripe.png\">";
    arr[49].picture = "<img src = \"image/red%20fish%20stripe.png\"><img src = \"image/red%20fish%20stripe.png\">";
    arr[50].picture = "<img src = \"image/red%20fish%20stripe.png\"><img src = \"image/red%20fish%20stripe.png\"><img src = \"image/red%20fish%20stripe.png\">";
    arr[51].picture = "<img src = \"image/red%20fish%20full.png\">";
    arr[52].picture = "<img src = \"image/red%20fish%20full.png\"><img src = \"image/red%20fish%20full.png\">";
    arr[53].picture = "<img src = \"image/red%20fish%20full.png\"><img src = \"image/red%20fish%20full.png\"><img src = \"image/red%20fish%20full.png\">";
    arr[54].picture = "<img src = \"image/green%20cat%20empty.png\">";
    arr[55].picture = "<img src = \"image/green%20cat%20empty.png\"><img src = \"image/green%20cat%20empty.png\">";
    arr[56].picture = "<img src = \"image/green%20cat%20empty.png\"><img src = \"image/green%20cat%20empty.png\"><img src = \"image/green%20cat%20empty.png\">";
    arr[57].picture = "<img src = \"image/green%20cat%20stripe.png\">";
    arr[58].picture = "<img src = \"image/green%20cat%20stripe.png\"><img src = \"image/green%20cat%20stripe.png\">";
    arr[59].picture = "<img src = \"image/green%20cat%20stripe.png\"><img src = \"image/green%20cat%20stripe.png\"><img src = \"image/green%20cat%20stripe.png\">";
    arr[60].picture = "<img src = \"image/green%20cat%20full.png\">";
    arr[61].picture = "<img src = \"image/green%20cat%20full.png\"><img src = \"image/green%20cat%20full.png\">";
    arr[62].picture = "<img src = \"image/green%20cat%20full.png\"><img src = \"image/green%20cat%20full.png\"><img src = \"image/green%20cat%20full.png\">";
    arr[63].picture = "<img src = \"image/green%20paw%20empty.png\">";
    arr[64].picture = "<img src = \"image/green%20paw%20empty.png\"><img src = \"image/green%20paw%20empty.png\">";
    arr[65].picture = "<img src = \"image/green%20paw%20empty.png\"><img src = \"image/green%20paw%20empty.png\"><img src = \"image/green%20paw%20empty.png\">";
    arr[66].picture = "<img src = \"image/green%20paw%20stripe.png\">";
    arr[67].picture = "<img src = \"image/green%20paw%20stripe.png\"><img src = \"image/green%20paw%20stripe.png\">";
    arr[68].picture = "<img src = \"image/green%20paw%20stripe.png\"><img src = \"image/green%20paw%20stripe.png\"><img src = \"image/green%20paw%20stripe.png\">";
    arr[69].picture = "<img src = \"image/green%20paw%20full.png\">";
    arr[70].picture = "<img src = \"image/green%20paw%20full.png\"><img src = \"image/green%20paw%20full.png\">";
    arr[71].picture = "<img src = \"image/green%20paw%20full.png\"><img src = \"image/green%20paw%20full.png\"><img src = \"image/green%20paw%20full.png\">";
    arr[72].picture = "<img src = \"image/green%20fish%20empty.png\">";
    arr[73].picture = "<img src = \"image/green%20fish%20empty.png\"><img src = \"image/green%20fish%20empty.png\">";
    arr[74].picture = "<img src = \"image/green%20fish%20empty.png\"><img src = \"image/green%20fish%20empty.png\"><img src = \"image/green%20fish%20empty.png\">";
    arr[75].picture = "<img src = \"image/green%20fish%20stripe.png\">";
    arr[76].picture = "<img src = \"image/green%20fish%20stripe.png\"><img src = \"image/green%20fish%20stripe.png\">";
    arr[77].picture = "<img src = \"image/green%20fish%20stripe.png\"><img src = \"image/green%20fish%20stripe.png\"><img src = \"image/green%20fish%20stripe.png\">";
    arr[78].picture = "<img src = \"image/green%20fish%20full.png\">";
    arr[79].picture = "<img src = \"image/green%20fish%20full.png\"><img src = \"image/green%20fish%20full.png\">";
    arr[80].picture = "<img src = \"image/green%20fish%20full.png\"><img src = \"image/green%20fish%20full.png\"><img src = \"image/green%20fish%20full.png\">";
}